### ISSUE TITLE
This package not found

### ISSUE THREAD

**Issue by larryli** [alibabacloud-sdk-php/dysmsapi#1]
Missing https://packagist.org/packages/alibabacloud/dysmsapi

**Comment by songshenzong** [comment]
> Missing https://packagist.org/packages/alibabacloud/dysmsapi

We are synchronizing and replying to you when we have finished.

**Comment by songshenzong** [comment]
> Missing https://packagist.org/packages/alibabacloud/dysmsapi

Hello, dependency packages have been synchronized. We will update the instructions later.

**Comment by larryli** [comment]
o(￣▽￣)ｄ👍
